openapi: 3.0.3
info:
  version: 1.1.4
  title: GitHub v3 REST API
  description: GitHub's v3 REST API.
  license:
    name: MIT
    url: https://spdx.org/licenses/MIT
  termsOfService: https://docs.github.com/articles/github-terms-of-service
  contact:
    name: Support
    url: https://support.github.com/contact?tags=dotcom-rest-api
  x-github-plan: api.github.com
servers:
- url: https://api.github.com
components:
  schemas:
    root:
      type: object
      properties:
        current_user_url:
          type: string
          format: uri-template
        current_user_authorizations_html_url:
          type: string
          format: uri-template
        authorizations_url:
          type: string
          format: uri-template
        code_search_url:
          type: string
          format: uri-template
        commit_search_url:
          type: string
          format: uri-template
        emails_url:
          type: string
          format: uri-template
        emojis_url:
          type: string
          format: uri-template
        events_url:
          type: string
          format: uri-template
        feeds_url:
          type: string
          format: uri-template
        followers_url:
          type: string
          format: uri-template
        following_url:
          type: string
          format: uri-template
        gists_url:
          type: string
          format: uri-template
        hub_url:
          type: string
          format: uri-template
          deprecated: true
        issue_search_url:
          type: string
          format: uri-template
        issues_url:
          type: string
          format: uri-template
        keys_url:
          type: string
          format: uri-template
        label_search_url:
          type: string
          format: uri-template
        notifications_url:
          type: string
          format: uri-template
        organization_url:
          type: string
          format: uri-template
        organization_repositories_url:
          type: string
          format: uri-template
        organization_teams_url:
          type: string
          format: uri-template
        public_gists_url:
          type: string
          format: uri-template
        rate_limit_url:
          type: string
          format: uri-template
        repository_url:
          type: string
          format: uri-template
        repository_search_url:
          type: string
          format: uri-template
        current_user_repositories_url:
          type: string
          format: uri-template
        starred_url:
          type: string
          format: uri-template
        starred_gists_url:
          type: string
          format: uri-template
        topic_search_url:
          type: string
          format: uri-template
        user_url:
          type: string
          format: uri-template
        user_organizations_url:
          type: string
          format: uri-template
        user_repositories_url:
          type: string
          format: uri-template
        user_search_url:
          type: string
          format: uri-template
      required:
      - current_user_url
      - current_user_authorizations_html_url
      - authorizations_url
      - code_search_url
      - commit_search_url
      - emails_url
      - emojis_url
      - events_url
      - feeds_url
      - followers_url
      - following_url
      - gists_url
      - issue_search_url
      - issues_url
      - keys_url
      - label_search_url
      - notifications_url
      - organization_url
      - organization_repositories_url
      - organization_teams_url
      - public_gists_url
      - rate_limit_url
      - repository_url
      - repository_search_url
      - current_user_repositories_url
      - starred_url
      - starred_gists_url
      - user_url
      - user_organizations_url
      - user_repositories_url
      - user_search_url
    basic-error:
      title: Basic Error
      description: Basic Error
      type: object
      properties:
        message:
          type: string
        documentation_url:
          type: string
        url:
          type: string
        status:
          type: string
    api-overview:
      title: Api Overview
      description: Api Overview
      type: object
      properties:
        verifiable_password_authentication:
          type: boolean
          example: true
        ssh_key_fingerprints:
          type: object
          properties:
            SHA256_RSA:
              type: string
            SHA256_DSA:
              type: string
            SHA256_ECDSA:
              type: string
            SHA256_ED25519:
              type: string
        ssh_keys:
          type: array
          items:
            type: string
          example:
          - ssh-ed25519 ABCDEFGHIJKLMNOPQRSTUVWXYZ
        hooks:
          type: array
          items:
            type: string
          example:
          - 192.0.2.1
        github_enterprise_importer:
          type: array
          items:
            type: string
          example:
          - 192.0.2.1
        web:
          type: array
          items:
            type: string
          example:
          - 192.0.2.1
        api:
          type: array
          items:
            type: string
          example:
          - 192.0.2.1
        git:
          type: array
          items:
            type: string
          example:
          - 192.0.2.1
        packages:
          type: array
          items:
            type: string
          example:
          - 192.0.2.1
        pages:
          type: array
          items:
            type: string
          example:
          - 192.0.2.1
        importer:
          type: array
          items:
            type: string
          example:
          - 192.0.2.1
        actions:
          type: array
          items:
            type: string
          example:
          - 192.0.2.1
        actions_macos:
          type: array
          items:
            type: string
          example:
          - 192.0.2.1
        codespaces:
          type: array
          items:
            type: string
          example:
          - 192.0.2.1
        dependabot:
          type: array
          items:
            type: string
          example:
          - 192.0.2.1
        copilot:
          type: array
          items:
            type: string
          example:
          - 192.0.2.1
        domains:
          type: object
          properties:
            website:
              type: array
              items:
                type: string
                example:
                - example.com
            codespaces:
              type: array
              items:
                type: string
                example:
                - example.com
            copilot:
              type: array
              items:
                type: string
                example:
                - example.com
            packages:
              type: array
              items:
                type: string
                example:
                - example.com
            actions:
              type: array
              items:
                type: string
                example:
                - example.com
            actions_inbound:
              type: object
              properties:
                full_domains:
                  type: array
                  items:
                    type: string
                    example:
                    - example.com
                wildcard_domains:
                  type: array
                  items:
                    type: string
                    example:
                    - example.com
            artifact_attestations:
              type: object
              properties:
                trust_domain:
                  type: string
                  example:
                  - example
                services:
                  type: array
                  items:
                    type: string
                    example:
                    - example.com
      required:
      - verifiable_password_authentication
  examples:
    root:
      value:
        current_user_url: https://api.github.com/user
        current_user_authorizations_html_url: https://github.com/settings/connections/applications{/client_id}
        authorizations_url: https://api.github.com/authorizations
        code_search_url: https://api.github.com/search/code?q={query}{&page,per_page,sort,order}
        commit_search_url: https://api.github.com/search/commits?q={query}{&page,per_page,sort,order}
        emails_url: https://api.github.com/user/emails
        emojis_url: https://api.github.com/emojis
        events_url: https://api.github.com/events
        feeds_url: https://api.github.com/feeds
        followers_url: https://api.github.com/user/followers
        following_url: https://api.github.com/user/following{/target}
        gists_url: https://api.github.com/gists{/gist_id}
        hub_url: https://api.github.com/hub
        issue_search_url: https://api.github.com/search/issues?q={query}{&page,per_page,sort,order}
        issues_url: https://api.github.com/issues
        keys_url: https://api.github.com/user/keys
        label_search_url: https://api.github.com/search/labels?q={query}&repository_id={repository_id}{&page,per_page}
        notifications_url: https://api.github.com/notifications
        organization_url: https://api.github.com/orgs/{org}
        organization_repositories_url: https://api.github.com/orgs/{org}/repos{?type,page,per_page,sort}
        organization_teams_url: https://api.github.com/orgs/{org}/teams
        public_gists_url: https://api.github.com/gists/public
        rate_limit_url: https://api.github.com/rate_limit
        repository_url: https://api.github.com/repos/{owner}/{repo}
        repository_search_url: https://api.github.com/search/repositories?q={query}{&page,per_page,sort,order}
        current_user_repositories_url: https://api.github.com/user/repos{?type,page,per_page,sort}
        starred_url: https://api.github.com/user/starred{/owner}{/repo}
        starred_gists_url: https://api.github.com/gists/starred
        topic_search_url: https://api.github.com/search/topics?q={query}{&page,per_page}
        user_url: https://api.github.com/users/{user}
        user_organizations_url: https://api.github.com/user/orgs
        user_repositories_url: https://api.github.com/users/{user}/repos{?type,page,per_page,sort}
        user_search_url: https://api.github.com/search/users?q={query}{&page,per_page,sort,order}
    api-overview:
      value:
        verifiable_password_authentication: true
        ssh_key_fingerprints:
          SHA256_RSA: 1234567890
          SHA256_DSA: 1234567890
          SHA256_ECDSA: 1234567890
          SHA256_ED25519: 1234567890
        ssh_keys:
        - ssh-ed25519 ABCDEFGHIJKLMNOPQRSTUVWXYZ
        - ecdsa-sha2-nistp256 ABCDEFGHIJKLMNOPQRSTUVWXYZ
        - ssh-rsa ABCDEFGHIJKLMNOPQRSTUVWXYZ
        hooks:
        - 192.0.2.1
        github_enterprise_importer:
        - 192.0.2.1
        web:
        - 192.0.2.1
        api:
        - 192.0.2.1
        git:
        - 192.0.2.1
        packages:
        - 192.0.2.1
        pages:
        - 192.0.2.1
        importer:
        - 192.0.2.1
        actions:
        - 192.0.2.1
        actions_macos:
        - 192.0.2.1
        dependabot:
        - 192.0.2.1
        copilot:
        - 192.0.2.1
        domains:
          website:
          - '*.example.com'
          codespaces:
          - '*.example.com'
          copilot:
          - '*.example.com'
          packages:
          - '*.example.com'
    octocat:
      value: "               MMM.           .MMM\n               MMMMMMMMMMMMMMMMMMM\n               MMMMMMMMMMMMMMMMMMM      ___________________________________\n              MMMMMMMMMMMMMMMMMMMMM    |                                   |\n             MMMMMMMMMMMMMMMMMMMMMMM   | Avoid administrative distraction. |\n            MMMMMMMMMMMMMMMMMMMMMMMM   |_   _______________________________|\n            MMMM::- -:::::::- -::MMMM    |/\n             MM~:~ 00~:::::~ 00~:~MM\n        .. MMMMM::.00:::+:::.00::MMMMM ..\n              .MM::::: ._. :::::MM.\n                 MMMM;:::::;MMMM\n          -MM        MMMMMMM\n          ^  M+     MMMMMMMMM\n              MMMMMMM MM MM MM\n                   MM MM MM MM\n                   MM MM MM MM\n                .~~MM~MM~MM~MM~~.\n             ~~~~MM:~MM~~~MM~:MM~~~~\n            ~~~~~~==~==~~~==~==~~~~~~\n             ~~~~~~==~==~==~==~~~~~~\n                 :~==~==~==~==~~\n"
  responses:
    not_found:
      description: Resource not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/basic-error'
    not_modified:
      description: Not modified
security: []
tags:
- name: meta
  description: Endpoints that give information about the API.
externalDocs:
  description: GitHub v3 REST API
  url: https://docs.github.com/rest/
paths:
  /:
    get:
      summary: GitHub API Root
      description: Get Hypermedia links to resources accessible in GitHub's REST API
      tags:
      - meta
      operationId: meta/root
      responses:
        '200':
          description: Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/root'
              examples:
                default:
                  $ref: '#/components/examples/root'
      x-github:
        githubCloudOnly: false
        enabledForGitHubApps: true
        category: meta
        subcategory: meta
      externalDocs:
        description: API method documentation
        url: https://docs.github.com/rest/meta/meta#github-api-root
  /meta:
    get:
      summary: Get GitHub meta information
      description: 'Returns meta information about GitHub, including a list of GitHub''s IP addresses. For more information, see "[About GitHub''s IP addresses](https://docs.github.com/articles/about-github-s-ip-addresses/)."


        The API''s response also includes a list of GitHub''s domain names.


        The values shown in the documentation''s response are example values. You must always query the API directly to get the latest values.


        > [!NOTE]

        > This endpoint returns both IPv4 and IPv6 addresses. However, not all features support IPv6. You should refer to the specific documentation for each feature to determine if IPv6 is supported.'
      tags:
      - meta
      operationId: meta/get
      externalDocs:
        description: API method documentation
        url: https://docs.github.com/rest/meta/meta#get-apiname-meta-information
      parameters: []
      responses:
        '200':
          description: Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/api-overview'
              examples:
                default:
                  $ref: '#/components/examples/api-overview'
        '304':
          $ref: '#/components/responses/not_modified'
      x-github:
        githubCloudOnly: false
        enabledForGitHubApps: true
        category: meta
        subcategory: meta
  /octocat:
    get:
      summary: Get Octocat
      description: Get the octocat as ASCII art
      tags:
      - meta
      operationId: meta/get-octocat
      parameters:
      - name: s
        in: query
        description: The words to show in Octocat's speech bubble
        schema:
          type: string
        required: false
      responses:
        '200':
          description: Response
          content:
            application/octocat-stream:
              schema:
                type: string
              examples:
                default:
                  $ref: '#/components/examples/octocat'
      externalDocs:
        description: API method documentation
        url: https://docs.github.com/rest/meta/meta#get-octocat
      x-github:
        githubCloudOnly: false
        enabledForGitHubApps: true
        category: meta
        subcategory: meta
  /versions:
    get:
      summary: Get all API versions
      description: Get all supported GitHub API versions.
      tags:
      - meta
      operationId: meta/get-all-versions
      externalDocs:
        description: API method documentation
        url: https://docs.github.com/rest/meta/meta#get-all-api-versions
      responses:
        '200':
          description: Response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                  format: date
                  example: '2021-01-01'
              examples:
                default:
                  value:
                  - '2021-01-01'
                  - '2021-06-01'
                  - '2022-01-01'
        '404':
          $ref: '#/components/responses/not_found'
      x-github:
        githubCloudOnly: false
        enabledForGitHubApps: true
        category: meta
        subcategory: meta
  /zen:
    get:
      summary: Get the Zen of GitHub
      description: Get a random sentence from the Zen of GitHub
      tags:
      - meta
      operationId: meta/get-zen
      externalDocs:
        description: API method documentation
        url: https://docs.github.com/rest/meta/meta#get-the-zen-of-github
      responses:
        '200':
          description: Response
          content:
            text/plain:
              schema:
                type: string
              examples:
                default:
                  summary: Example response
                  value: Responsive is better than fast
      x-github:
        githubCloudOnly: false
        enabledForGitHubApps: true
        category: meta
        subcategory: meta
